---
title: "Likelihood theory for finite population"
author: "Markus Stein"
date: "July 11, 2019"
output:
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Real life meaning of probability
What are the set of all possible outcomes?  

- K. Pearson - probability distributions are observable by collecting **lots of data**. 

- W. Gosset - attempted to describe experimental design.

- R. A. Fisher - set of all possible random assignments, **permutation**.
    * How big is the set of all permutations?
    * And in observational studies?
    
### **Finite population** meaning of probability is well estabilished!


## Finite population likelihood ideas
Assume a random variable $Y \sim Bernoulli(\pi)$, assume that we observe a population $y_1, \ldots, y_N$ from $Y$.


### Population likelihood
If we observed all $y_1, \ldots, y_N$, the **population likelihood** is
$$ L_{pop}(\theta) = \prod_{i=1}^{N} \pi^{y_i} \: (1-\pi)^{(1-y_i)}$$



## Sample likelihood
- Now, assume that we only observe a sample of size $n$ form the population $y_1, \ldots, y_N$.  

- Then, we define the sample likelihood  
$$ L_{sample}(\theta) = \prod_{i=1}^{n} \pi^{y_i} \: (1-\pi)^{(1-y_i)} $$

- Can $n\rightarrow \infty$?

## Monte Carlo likelihood approximation
- Consider the $N - n$ non-observed units...

- To generate not observed units given the observed.


## Modelos Condicionais - Ancilaridade
- Quando um modelo não é completo, a estatística suficiente minimal vai conter alguma estatística ancilar;

\vspace{0.5cm}

- Assim, sua dimensão será maior do que a do espaço paramétrico; 

\vspace{0.5cm}

- Então, como usar estatística ancilar para reduzir ainda mais a informação suficiente e minimal?

## Modelos Condicionais - Ancilaridade
- Seja $N$ uma variável aleatória que assume valores $1, 2, \ldots$ com probabilidades  $\pi_1, \pi_2, \ldots$.

\vspace{0.5cm}

- Dado que observamos $N=n$, então realizamos $n$ ensaios $Bernoulli(p)$ independentes e $X_n$ é o número de sucessos.

\vspace{0.5cm}

- A estatística $W_N(X) = (N, X_N)$ é suficiente minimal e $N$ é uma estatística ancilar:
    + $N$ não fornece informação sobre $p$;
    + porém diz quanto de informação sobre $p$ está contida em $X_N$;
    

## Modelos Condicionais - Ancilaridade
"$(N, X_N)$ é estatística suficiente minimal e $N$ é uma estatística ancilar."

\vspace{0.5cm}

1. se o valor observado $n$ é grande $\rightarrow$ $X_N$ muito informativo.   

2. se $n$ é muito pequeno $\rightarrow$ $X_N$ conterá pouca informação.

\vspace{0.5cm}

- Condicionando em $N=n$, vamos de $W_N(x)=(N, X_N)$ para $S_n(x)=X_n$.
    + Como $X_n$ é completa, o modelo condicional é completo.


